### PR TITLE
Streamling getting started

### PR DESCRIPTION
**Pull request by branning**
I had a few problems getting started, and once I fixed them I figured it would be helpful to share them. Many rounds of yak shaving later, here's some stuff:
- script to install dependencies and build `csqlite.o`
  - I had some trouble building `csqlite.o`, as the makefile in `flibs-0.9/flibs/src/sqlite/` seems to be intentionally incomplete. Modified the makefile there, it won't support all platforms, but in its present form it supports 0 platforms!
- makefile to build fortran_fcgi
  - `make` will build everything
  - `make clean` will delete what you built
- `restart.sh` script
- updated `README.md` to reflect the above changes, and tested on a fresh Ubuntu 14.04 machine at Digital Ocean

Thanks for the cool project!

### CODE REVIEW

**Comment by mapmeld** [comment]
awesome, awesome

SQLite came together at the very end, with some difficulties getting it compiled. I prefer your way of handling that here.

**Comment by branning** [comment]
Thanks for taking a look, and accepting the MR!

I'm interested in submitting a patch to https://github.com/TechEmpower/FrameworkBenchmarks, I think it would induce all kinds of complicated feelings to see `Fortran` in the list of languages there. They have some kind of disqualification for frameworks that use `sqlite`, though I do see that the `lwan` framework is using it currently. I looked into how much work it would be to wrap a minimal interface to Postgres' `libpq` in Fortran, and the answer is _some_.

**Comment by mapmeld** [comment]
That sounds really cool!

Since you're good at build scripts, maybe you would be interested in another project which I've connected with... I figured out how to install post-quantum encryption tool CodeCrypt on OSX but I don't want to mess up the build script for everyone ( https://github.com/exaexa/codecrypt/issues/15 )   Can you take a look at it?

**Comment by branning** [comment]
Sure @mapmeld I'm looking at it now.

**Pull request merged**
